apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: consul-dc1
spec:
  serviceName: "consul"
  replicas: 5
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:1.15.4
        ports:
        - containerPort: 8500
          name: http
        - containerPort: 8600
          name: dns
        - containerPort: 8301
          name: serflan-tcp
        - containerPort: 8301
          name: serflan-udp
          protocol: UDP
        - containerPort: 8300
          name: server
        volumeMounts:
        - name: consul-data
          mountPath: /consul/data
        - name: consul-config-dc1
          mountPath: /consul/config
      volumes:
      - name: consul-config-dc1
        configMap:
          name: consul-config-dc1
  volumeClaimTemplates:
  - metadata:
      name: consul-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: consul-dc1
spec:
  ports:
  - port: 8500
    name: http
  - port: 8600
    name: dns
  - port: 8301
    name: serflan-tcp
  - port: 8301
    name: serflan-udp
    protocol: UDP
  - port: 8300
    name: server
  clusterIP: None
  selector:
    app: consul